appartenir_index:
    path:     /
    defaults: { _controller: "AppBundle:Appartenir:index" }
    methods:  GET

appartenir_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Appartenir:show" }
    methods:  GET

appartenir_new:
    path:     /new
    defaults: { _controller: "AppBundle:Appartenir:new" }
    methods:  [GET, POST]

appartenir_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Appartenir:edit" }
    methods:  [GET, POST]

appartenir_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Appartenir:delete" }
    methods:  DELETE
