app_groups:
    resource: "@AppBundle/Resources/config/routing/groups.yml"
    prefix:   /groups

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_appartenir:
    resource: "@AppBundle/Resources/config/routing/appartenir.yml"
    prefix:   /appartenir
