<?php

namespace BudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CagnottesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CagnottesRepository extends EntityRepository
{
}
